name: widefield
channels: [conda-forge, defaults]
dependencies:
  - python>=3.10
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - pywavelets
  - jupyterlab
  - pip
  - pip:
      - networkx
# R deps installed separately:
# Rscript -e "install.packages(c('lme4','broom','dplyr'), repos='https://cloud.r-project.org')"
